version: 2.1

jobs:
  tox:
    resource_class: large
    parameters:
      toxenv:
        type: string
    machine:
      image: ubuntu-2004:202101-01
    steps:
      - checkout
      - run: 
          name: Install dependencies
          command: etc/testing/circle/install.sh
      - run: 
          name: Start minikube
          command: etc/testing/circle/start-minikube.sh
      - run:
          name: Deploy pachyderm
          command: etc/testing/circle/deploy-pachyderm.sh 
      - run: 
          command: python3 -m tox
          environment:
            TOXENV: << parameters.toxenv >>
      - run:
          when: on_fail
          command: etc/testing/circle/kube_debug.sh

workflows:
  circleci:
    jobs:
      - tox:
          matrix:
            parameters:
              toxenv:
              - py36
              - py39
              - lint
              - examples
